backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: "This Week", name: thisweek, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
  
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/get-involved/index.md"
        label: "Get Involved"
        name: "get-involved"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/get-involved"}
          - {label: "Title", name: title, widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/projects/index.md"
        label: "Projects"
        name: "projects"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/projects"}
          - {label: "Title", name: title, widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
      
